# Generated by Django 3.2.18 on 2023-03-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile_no',
            new_name='mobileno',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
